u = input("enter intial velocity :")
u = int(u)
a = input("enter accleration :")
a = int(a)
t = input("enter time :")
t = int(t)
print("the final velocity is v =" ,u +a*t)

u = input("enter intial velocity :")
u = int(u)
a = input("enter accleration :")
a = int(a)
s = input("enter the distance travelled :")
s = int(s)
print("the final velocity is v =" ,u*u + 2*a*s)

u = input("enter intial velocity :")
u = int(u)
a = input("enter accleration :")
a = int(a)
t = input("enter time :")
t = int(t)
print("the displacment covered is s=" ,u*t + 0.5*a*t*t)
